In [2]:
# Numpy
#What is NumPy?
#NumPy = Numerical Python library
#Used to handle N-Dimensional arrays

In [3]:
# Numpy -- data anlysis, buisness anlaysis, machine leanring, deep learning, gen ai  , computer vision 
#uses of numpy:

#1- arithmetic operation 
#2- statistical operation 
#3- bitwise opearatro 
#4- copy & view array 
#5- stacking
#6- matrix operation 
#7- linear algebra 
#8- broadcasting
#9- math operation 
#10- search, sorting, counting 

In [4]:
#if you want to any pkg version -- __version__ 

In [5]:
# There are total of 256 operations in numpy.

In [6]:
import numpy as np

In [9]:
np.__version__

'1.26.4'

In [10]:
np. 
# tab complete to see all the operations in numpy.

SyntaxError: invalid syntax (1702554547.py, line 1)

In [11]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [12]:
type(my_list)

list

In [13]:
# convert list to array
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [14]:
type(arr)

numpy.ndarray

In [15]:
# create array from 0 to 9
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(10, 20) # create array from 10 to 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(10, 20, 3) # create array from 10 to 19 with step of 3

array([10, 13, 16, 19])

In [18]:
np.zeros(5) # create array of zeros with length 5

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros(5, dtype = int) # create array of zeros with length 5 and data type int
# 1d array 

array([0, 0, 0, 0, 0])

In [20]:
np.zeros((2,2)) #2d array 

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros((2,2), dtype=int) # 2d array with data type int

array([[0, 0],
       [0, 0]])

In [22]:
np.zeros((2,2), dtype=complex) 

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [23]:
np.zeros((2,2), dtype=str) 

array([['', ''],
       ['', '']], dtype='<U1')

In [24]:
np.zeros((5,10), dtype=int) # 2d array with 5 rows and 10 columns with data type int

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.ones(10) # create array of ones with length 10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones((3,3), dtype = int) # 2d array with 3 rows and 3 columns with data type int

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
np.twos(3) 
# np.twos is not a valid function in numpy. To create an array of twos, you can use np.ones and multiply it by 2:

AttributeError: module 'numpy' has no attribute 'twos'

In [28]:
# syntax of np.random.rand is np.random.rand(d0, d1, ..., dn) where d0, d1, ..., dn are the dimensions of the output array.

In [29]:
np.random.rand(4) 
# create an array of 4 random numbers between 0 and 1 from a uniform distribution.

array([0.41177969, 0.62837181, 0.04417588, 0.23250534])

In [30]:
np.random.rand(2,2) 
# create a 2d array of random numbers between 0 and 1 from a uniform distribution with 2 rows and 2 columns.

array([[0.48482116, 0.15764521],
       [0.828049  , 0.33852625]])

In [31]:
np.random.randint(3) # create an array of random integers between 0 and 2 with length 3.

0

In [32]:
np.random.randint(10, 15, size=3) # create an array of random integers between 10 and 14 with length 3.

array([14, 12, 11])

In [33]:
np.random.randint(1,5,4) # create an array of random integers between 1 and 4 with length 4.

array([1, 4, 2, 3])

In [34]:
np.random.randint(5,2,3)
# it is error because the first argument is greater than the second argument. The first argument should be less than the second argument.

ValueError: low >= high

In [ ]:
np.random.randint(-5,2,3)

array([-3, -2, -5])

In [35]:
np.random.randint(10,40,(10,10)) # create a 2d array of random integers between 10 and 39 with shape (10,10).

array([[30, 10, 36, 11, 32, 18, 38, 24, 13, 22],
       [13, 28, 24, 38, 34, 35, 30, 29, 33, 13],
       [37, 37, 36, 24, 19, 12, 16, 33, 21, 18],
       [25, 16, 10, 27, 34, 10, 13, 26, 34, 38],
       [39, 15, 16, 37, 30, 19, 39, 20, 36, 18],
       [37, 24, 20, 30, 38, 28, 29, 13, 25, 26],
       [26, 32, 12, 35, 17, 16, 22, 25, 14, 30],
       [30, 23, 24, 20, 21, 11, 29, 24, 12, 37],
       [34, 26, 18, 12, 38, 16, 34, 27, 17, 22],
       [12, 34, 14, 25, 30, 38, 36, 31, 10, 29]])

In [39]:
ri = np.random.randint(10,40,(3,5))
ri

array([[39, 35, 14, 29, 34],
       [16, 31, 37, 26, 15],
       [13, 24, 15, 23, 25]])

In [40]:
len(ri) #it will print rows bydefault.

3

In [41]:
ri.shape # it will print the shape of the array. It will print (10,10) because it is a 2d array with 10 rows and 10 columns.

(3, 5)

In [42]:
id(ri)

2501727031568

In [43]:
ri

array([[39, 35, 14, 29, 34],
       [16, 31, 37, 26, 15],
       [13, 24, 15, 23, 25]])

In [44]:
# Slicing of numpy array

In [45]:
ri[:]

array([[39, 35, 14, 29, 34],
       [16, 31, 37, 26, 15],
       [13, 24, 15, 23, 25]])

In [47]:
ri[1] # it will print the second row of the array because indexing starts from 0.

array([16, 31, 37, 26, 15])

In [48]:
ri[0:3]

array([[39, 35, 14, 29, 34],
       [16, 31, 37, 26, 15],
       [13, 24, 15, 23, 25]])

In [50]:
ri_1 = np.random.randint(10,40,(10,10))
ri_1

array([[29, 32, 25, 14, 17, 23, 31, 17, 30, 19],
       [20, 17, 32, 30, 31, 29, 15, 32, 14, 35],
       [37, 18, 25, 17, 39, 32, 20, 16, 24, 29],
       [17, 24, 23, 14, 36, 15, 25, 27, 25, 39],
       [35, 30, 20, 22, 11, 37, 24, 19, 31, 28],
       [19, 17, 15, 19, 33, 28, 17, 19, 21, 11],
       [36, 11, 18, 28, 23, 13, 28, 23, 25, 29],
       [25, 34, 16, 23, 26, 23, 19, 20, 32, 34],
       [30, 26, 39, 31, 15, 34, 31, 21, 11, 25],
       [29, 31, 37, 17, 31, 35, 26, 22, 16, 22]])

In [52]:
ri_1.shape

(10, 10)

In [53]:
ri_1[3:8]

array([[17, 24, 23, 14, 36, 15, 25, 27, 25, 39],
       [35, 30, 20, 22, 11, 37, 24, 19, 31, 28],
       [19, 17, 15, 19, 33, 28, 17, 19, 21, 11],
       [36, 11, 18, 28, 23, 13, 28, 23, 25, 29],
       [25, 34, 16, 23, 26, 23, 19, 20, 32, 34]])

In [54]:
ri_1[3,8]

25

In [57]:
ri_1[-5]

array([19, 17, 15, 19, 33, 28, 17, 19, 21, 11])

In [58]:
ri_1[-5,-3]

19

In [60]:
ri_1

array([[29, 32, 25, 14, 17, 23, 31, 17, 30, 19],
       [20, 17, 32, 30, 31, 29, 15, 32, 14, 35],
       [37, 18, 25, 17, 39, 32, 20, 16, 24, 29],
       [17, 24, 23, 14, 36, 15, 25, 27, 25, 39],
       [35, 30, 20, 22, 11, 37, 24, 19, 31, 28],
       [19, 17, 15, 19, 33, 28, 17, 19, 21, 11],
       [36, 11, 18, 28, 23, 13, 28, 23, 25, 29],
       [25, 34, 16, 23, 26, 23, 19, 20, 32, 34],
       [30, 26, 39, 31, 15, 34, 31, 21, 11, 25],
       [29, 31, 37, 17, 31, 35, 26, 22, 16, 22]])

In [61]:
ri_1[::3] #it will print every 3rd row of the array starting from the first row.

array([[29, 32, 25, 14, 17, 23, 31, 17, 30, 19],
       [17, 24, 23, 14, 36, 15, 25, 27, 25, 39],
       [36, 11, 18, 28, 23, 13, 28, 23, 25, 29],
       [29, 31, 37, 17, 31, 35, 26, 22, 16, 22]])

In [62]:
ri_1[::-1] # it will reverse the array. It will print the array in reverse order.

array([[29, 31, 37, 17, 31, 35, 26, 22, 16, 22],
       [30, 26, 39, 31, 15, 34, 31, 21, 11, 25],
       [25, 34, 16, 23, 26, 23, 19, 20, 32, 34],
       [36, 11, 18, 28, 23, 13, 28, 23, 25, 29],
       [19, 17, 15, 19, 33, 28, 17, 19, 21, 11],
       [35, 30, 20, 22, 11, 37, 24, 19, 31, 28],
       [17, 24, 23, 14, 36, 15, 25, 27, 25, 39],
       [37, 18, 25, 17, 39, 32, 20, 16, 24, 29],
       [20, 17, 32, 30, 31, 29, 15, 32, 14, 35],
       [29, 32, 25, 14, 17, 23, 31, 17, 30, 19]])

In [63]:
ri_1[::-5]

array([[29, 31, 37, 17, 31, 35, 26, 22, 16, 22],
       [35, 30, 20, 22, 11, 37, 24, 19, 31, 28]])

In [66]:
ri_1

array([[29, 32, 25, 14, 17, 23, 31, 17, 30, 19],
       [20, 17, 32, 30, 31, 29, 15, 32, 14, 35],
       [37, 18, 25, 17, 39, 32, 20, 16, 24, 29],
       [17, 24, 23, 14, 36, 15, 25, 27, 25, 39],
       [35, 30, 20, 22, 11, 37, 24, 19, 31, 28],
       [19, 17, 15, 19, 33, 28, 17, 19, 21, 11],
       [36, 11, 18, 28, 23, 13, 28, 23, 25, 29],
       [25, 34, 16, 23, 26, 23, 19, 20, 32, 34],
       [30, 26, 39, 31, 15, 34, 31, 21, 11, 25],
       [29, 31, 37, 17, 31, 35, 26, 22, 16, 22]])

In [67]:
ri_1[:,2] #For column slicing, you can use the syntax array[:, column_index]. This will select all rows (:) and the specified column (column_index).

array([25, 32, 25, 23, 20, 15, 18, 16, 39, 37])

In [68]:
ri_1[2] #for row slicing, you can use the syntax array[row_index].

array([37, 18, 25, 17, 39, 32, 20, 16, 24, 29])

In [69]:
ri_1[:,-8]

array([25, 32, 25, 23, 20, 15, 18, 16, 39, 37])

In [71]:
ri_1[2:6,5:8] # it will print the subarray from row index 2 to 5 and column index 5 to 7.

array([[32, 20, 16],
       [15, 25, 27],
       [37, 24, 19],
       [28, 17, 19]])

In [72]:
ri_1[0:3,0:3]

array([[29, 32, 25],
       [20, 17, 32],
       [37, 18, 25]])

In [73]:
#reshape

In [78]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [82]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [83]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# numpy masking and filtering

In [86]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat.shape

(10, 10)

In [88]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [89]:
mat[mat<50] 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [90]:
mat[mat!=50] 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [91]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [92]:
b = np.arange(0,10,2) # create an array of even numbers from 0 to 8 with step of 2.
print(b)

[0 2 4 6 8]


In [94]:
f = np.identity(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [96]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(f1)
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened) 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [100]:
e1 = np.array([[1, 2], [3, 4]])
t = np.transpose(e1) # it will transpose the array. It will swap the rows and columns of the array.
print(t)

[[1 3]
 [2 4]]


In [101]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [[1 2]
 [3 4]]


In [102]:
# Stack arrays horizontal
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.hstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [1 2 3 4]


In [103]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [104]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [105]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [112]:
a = np.array([1, 2, 3])


In [114]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a, a3)  # Dot product of a and g
print("Dot product of a1 and a3:", dot_product)


Dot product of a1 and a3: 14


In [115]:
# 4. Statistical Functions

In [116]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [119]:
# Variance of an array
var = np.var(s)
print("Variance of s :", var)


Variance of s : 1.25


In [120]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [121]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [122]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


In [123]:
# 5. Linear Algebra Functions


In [124]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]]) 
matrix

array([[1, 2],
       [3, 4]])

In [125]:
# 6. Random Sampling Functions

In [126]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals) 

Random values: [0.91736952 0.11412047 0.77133093]


In [128]:
# Set seed for reproducibility
np.random.seed(0) 

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [131]:
# Generate random integers 
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints) 

Random integers: [9 3 5 2 4]


In [132]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


In [133]:
# 7. Boolean & Logical Functions

In [134]:
# Check if all elements are True

# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [135]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [136]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [137]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


In [138]:
# 8. Set Operations

In [139]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [140]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


In [141]:
# 9. Array Attribute Functions

In [142]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


In [143]:
# 10. Other Functions

In [144]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [145]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [146]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
